---------------------------------------
Begin Slurm Prolog: Sep-12-2024 14:31:20
Job ID:    1267319
User ID:   mghanem8
Account:   gts-agarg35
Job name:  SlurmPythonExample
Partition: gpu-rtx6000
QOS:       embers
---------------------------------------

The following have been reloaded with a version change:
  1) anaconda3/2022.05 => anaconda3/2022.05.0.1

/usr/local/pace-apps/lmod/lmod/init/bash: line 169: conda: command not found
Running the following command:
python train.py --config-name=train_diffusion_unet_ddim_hybrid_workspace.yaml task=orbit_dual_suture hydra.run.dir=/storage/home/hcoda1/7/mghanem8/codes/quest_v0/experiments/diffpolicy/orbit_dual_suture_50 training.seed=0 training.device=cuda:0 exp_name=orbit_dual_suture_50_single-cam logging.mode=online checkpoint.save_ckpt=True task.dataset.max_train_episodes=50
Traceback (most recent call last):
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 379, in _apply_overrides_to_config
    OmegaConf.update(cfg, key, value, merge=True)
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/omegaconf/omegaconf.py", line 729, in update
    root.__setattr__(last_key, value)
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 337, in __setattr__
    raise e
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 334, in __setattr__
    self.__set_impl(key, value)
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 318, in __set_impl
    self._set_item_impl(key, value)
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/omegaconf/basecontainer.py", line 547, in _set_item_impl
    self._validate_set(key, value)
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 180, in _validate_set
    target = self._get_node(key) if key is not None else self
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/omegaconf/_utils.py", line 900, in format_and_raise
    _raise(ex, cause)
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/omegaconf/_utils.py", line 798, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
omegaconf.errors.ConfigAttributeError: Key 'save_ckpt' is not in struct
    full_key: checkpoint.save_ckpt
    object_type=dict

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/home/hcoda1/7/mghanem8/codes/diffusion_policy/train.py", line 34, in <module>
    main()
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/hydra/main.py", line 90, in decorated_main
    _run_hydra(
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/hydra/_internal/utils.py", line 389, in _run_hydra
    _run_app(
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/hydra/_internal/utils.py", line 452, in _run_app
    run_and_report(
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/hydra/_internal/utils.py", line 216, in run_and_report
    raise ex
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/hydra/_internal/utils.py", line 453, in <lambda>
    lambda: hydra.run(
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 105, in run
    cfg = self.compose_config(
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 594, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 141, in load_configuration
    return self._load_configuration_impl(
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 265, in _load_configuration_impl
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File "/storage/home/hcoda1/7/mghanem8/.conda/envs/robodiff/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 381, in _apply_overrides_to_config
    raise ConfigCompositionException(
hydra.errors.ConfigCompositionException: Could not override 'checkpoint.save_ckpt'.
To append to your config use +checkpoint.save_ckpt=True
srun: error: atl1-1-03-003-21-0: task 0: Exited with exit code 1
